services:
  redis:
    image: redis
    ports:
      - "6379":"6379"
    extends:
      file: common-config.yml
      service: network-deploy-service

  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "vmammedov/configserver:s10"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "vmammedov/eurekaserver:s10"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_started #----------------
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    restart: always

  accounts:
    image: "vmammedov/accounts:s10"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      accountsdb:
        condition: service_healthy
      configserver:
        condition: service_started #----------------
      eurekaserver:
        condition: service_started #----------------
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "vmammedov/loans:s10"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_started #----------------
      eurekaserver:
        condition: service_started #----------------
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans1:
    image: "vmammedov/loans:s10"
    container_name: loans-ms1
    ports:
      - "8091:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      loansdb:
        condition: service_healthy
      configserver:
        condition: service_started #----------------
      eurekaserver:
        condition: service_started #----------------
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "vmammedov/cards:s10"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
    depends_on:
      cardsdb:
        condition: service_healthy
      configserver:
        condition: service_started #----------------
      eurekaserver:
        condition: service_started #----------------
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  
  gatewayserver:
    image: "vmammedov/gatewayserver:s10"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_DATA_REDIS_CONNECT-TIMEOUT: 2s
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_TIMEOUT: 1s
    depends_on:
      accounts:
        condition: service_started #----------------
      cards:
        condition: service_started #----------------
      loans:
        condition: service_started #----------------
      redis:
        condition: service_started #----------------
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: "bridge"