server:
  port: 9010

spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms

  rabbitmq:
    host: localhost
    port: 5672
    stream:
      username: guest
      password: guest