server:
  port: 8090

  servlet:
    context-path: "/api"

spring:
  application:
    name: "loans"
  profiles:
    active: "prod"

  datasource:
    url: jdbc:h2:mem:loansdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    show-sql: true

  sql:
    init:
      mode: always

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"