apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb-mysql-deployment
  labels:
    app: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
      - name: accountsdb-container
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: accountsdb
        volumeMounts:
        - name: accountsdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: accountsdb-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: accountsdb
  clusterIP: None
