apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb-mysql-deployment
  labels:
    app: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: cardsdb
        volumeMounts:
        - name: cardsdb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: cardsdb-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  ports:
  - port: 3308
    targetPort: 3306
  selector:
    app: cardsdb
  clusterIP: None